# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a921b2d5799594eacea3482a2f82db20b1d5f86c46cbc4bf0640b33539c3634864d2ea290814d23e66e93836daab2311d09a136f1f4808d640c9f4df85e423f

test:
  secret_key_base: b1e0983b58cfa927b93ad92c261eaa7ec11450feecd3e65c1070ece577cd1caaa4da8c0181c00d779c9a15fc228946ea1b3a15e12ec8e394c1aaadfe1652bc97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
